### ISSUE TITLE
Playing with yourself bug

### ISSUE THREAD

**Issue by Zomis** [Zomis/Server2#29]
Should I make it impossible to play against yourself, or should I make it possible to play against yourself?

**Comment by bruglesco** [comment]
I think you should leave it as a feature.

**Comment by FreezePhoenix** [comment]
I agree with leaving it, but I also think we should let people know that it exists *and* make it more accessible so that you don't have to purposely break it.

**Comment by Zomis** [comment]
How about a button that says "Play with yourself"? :P :D ;)

**Comment by Zomis** [comment]
Playing against yourself has been disabled for quite a while, and the overall inner workings of how games work is now different so this issue is no longer an issue.
