### ISSUE TITLE
Client: Fix PlayerEliminatedMessage for local play

### ISSUE THREAD

**Issue by Zomis** [Zomis/Server2#3]
When a game finishes locally, call the method for handling PlayerEliminated to show the message that the game has ended.

**Comment by Zomis** [comment]
After this line: https://github.com/Zomis/Server2/blob/master/games-vue-client/src/components/RoyalGameOfUR.vue#L171
Check `if (this.ur.isFinished)` and then do `this.gameOverMessage = { winner: true }`, then it will always say "You win", because when playing locally, you always win don't you? Or what should be shown then?

**Comment by ShipsWithCannons** [comment]
At that point, it should also no longer accept rolling the dice.

The proper message would indicate which player won, Red or Blue.

**Comment by Zomis** [comment]
@ShipsWithCannons That fix is easy, check that `!this.ur.finished` when rolling the dice.

**Comment by Zomis** [comment]
This is working very differently now using the game DSL system and is no longer an issue
