### ISSUE TITLE
[Hanabi] Notify players when the deck runs out that there is one round left

### ISSUE THREAD

**Issue by GustaMagik** [Zomis/Server2#52]

**Comment by Zomis** [comment]
Suggestions for how to notify? Could add a "Turns left" indicator or something, but not sure what the best indicator would be?

**Comment by GustaMagik** [comment]
I think a "popup" animation that states "last round" should be good enought

**Comment by Zomis** [comment]
This can be fixed entirely in `Hanabi.vue` by using a watch together with a computed property: https://vuejs.org/v2/guide/computed.html#Watchers
Make a computed property for `cardsLeft` which returns `this.view.cardsLeft` then watch the property `cardsLeft` and make something happen when `cardsLeft == 0` (probably add a data value such as `this.lastRound` and set that to true and make that trigger an animation when it happens)

**Comment by Zomis** [comment]
An option might be to indicate who the last player is that will perform an action. Can be done by changing `Hanabi.vue` and the `view`-section of `HanabiGame.kt`

**Comment by GustaMagik** [comment]
https://www.npmjs.com/package/vue-toasted
This might be a nice option for displaying notifications through-out the site.
@Zomis Opinions?

**Comment by Zomis** [comment]
@GustaMagik VuetifyJS provides many components that could be used https://vuetifyjs.com/en/components/api-explorer/ and VuetifyJS is already used in many parts of the project already. In this case, a Snackbar might be a good option: https://vuetifyjs.com/en/components/snackbars/
