### ISSUE TITLE
[Hanabi] Failures counting

### ISSUE THREAD

**Issue by Motsols** [Zomis/Server2#56]
Count it from 0 and up instead of down. Also be clear that by 3 the game is lost.

![image](https://user-images.githubusercontent.com/694935/81219638-59c8ce80-8fe0-11ea-8765-b4b271cc5166.png)

Maybe start with the text 0/3?

**Comment by Zomis** [comment]
This can be fixed quite easily by changing the `view` section in `HanabiGame.kt`, and the `Hanabi.vue` file.

There are a few different options about what to do:

- Rename the caption to "Lifes" / "Illegal moves left" / Something...
- Change to "Fails 0/3" as suggested
