### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Motsols** [Zomis/Server2#58]
Give players an incitament to play new games bay having achievements on their profile page that they play tic-tac-toe, hanabi, artax, etc.

Not that I really care about achievements but if they are for exploring something new or playing in a new way I like them. "Win 1000000 times" I really don't like.

**Comment by Zomis** [comment]
This is a biiiiiiiiiiiiiiiig issue (as in big scope, not high priority). Currently there's no player platform or anything of that kind. If the game would be on Steam, sure (which there are currently no real plans for).

**Comment by Motsols** [comment]
This would be to incite your logged in players to try your different games and also to incite people into making accounts in the first place. I was just throwing it out there.

**Comment by Zomis** [comment]
Inciting people to make accounts would be nice, but honestly I don't care that much about which games they play... most of them were just created to push the limits of what the game engine could do :)

**Comment by Zomis** [comment]
After playing a game on Boardgamearena.com I realized: I don't want achievements, I just want to let people play games.
