### ISSUE TITLE
[Hanabi] When giving colour clues, colour the button accordingly to the clue.

### ISSUE THREAD

**Issue by Etrisa** [Zomis/Server2#62]
![image](https://user-images.githubusercontent.com/10958425/81404711-6f500c80-9136-11ea-8d18-f8a8847f32f2.png)

**Comment by Zomis** [comment]
@GustaMagik This one is a little bit trickier considering how the action-system works. You'd probably need to add a special case to check if the action-button begins with `color-` and then adapt it accordingly.

**Comment by GustaMagik** [comment]
@Zomis was kinda simple but needed to read some documentation to find vuetify :class with array notation.
